import { createMDX } from 'fumadocs-mdx/next';

const withMDX = createMDX();

/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
  // We maintain our own AGENTS.md (generated by pnpm gen); stop Next from appending to it.
  agentRules: false,
};

export default withMDX(config);
