export interface ShowcaseEntry {
  id: string;
  name: string;
  url: string;
  by: string;
  /** What to steal (the idea, never the code or assets). */
  lessons: string[];
  why: string;
  tags: string[];
  /** ms to wait for intro animation before capture */
  settle?: number;
  /** click through a start screen: 'center' or a button name */
  start?: string;
  /** exact text of a consent control to click */
  dismiss?: string;
  mine?: boolean;
}

export const showcase: ShowcaseEntry[] = [
  {
    id: 'linear',
    name: 'Linear',
    url: 'https://linear.app',
    by: 'Linear',
    why: 'Restraint as a brand. A near-monochrome palette, one typeface family, and product UI treated as the hero image.',
    lessons: ['Show the real product, not an illustration of it', 'Let a single accent colour mean "interactive"', 'Tight, confident type with generous line-height in body'],
    tags: ['product', 'typography', 'dark'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    url: 'https://stripe.com',
    by: 'Stripe',
    why: 'The benchmark for gradients with purpose: colour carries energy while the grid and copy stay strict.',
    lessons: ['A living gradient can carry brand without a mascot', 'Dense information stays calm on a strict column grid', 'Micro-diagrams explain the product faster than paragraphs'],
    tags: ['gradient', 'grid', 'product'],
  },
  {
    id: 'lusion',
    name: 'Lusion',
    url: 'https://lusion.co',
    by: 'Lusion',
    why: 'WebGL as craft, not decoration: every scene reacts to the pointer and scroll, and the UI stays out of its way.',
    lessons: ['Interaction is the portfolio', 'Keep chrome minimal when the canvas is the content', 'Transitions between scenes sell continuity'],
    tags: ['webgl', '3d', 'studio'],
    settle: 22000,
  },
  {
    id: 'igloo',
    name: 'Igloo Inc.',
    url: 'https://www.igloo.inc',
    by: 'Igloo Inc. (built with Abeto)',
    why: 'Scroll as a camera. A single 3D world, cold material palette and sound design make a company page feel like an object.',
    lessons: ['One world, one camera path, many chapters', 'Material and lighting do the branding', 'Sound is an optional layer, not a default'],
    tags: ['webgl', 'scroll', 'award'],
    settle: 22000,
  },
  {
    id: 'rauno',
    name: 'Rauno Freiberg',
    url: 'https://rauno.me',
    by: 'Rauno Freiberg',
    why: 'Interaction details as the whole point. Small, precise prototypes and an interface that rewards curiosity.',
    lessons: ['Tiny interactions, done perfectly, beat big ones done roughly', 'Quiet typography lets craft show', 'Every hover and focus state is designed'],
    tags: ['interaction', 'minimal', 'personal'],
  },
  {
    id: 'emil',
    name: 'Emil Kowalski',
    url: 'https://emilkowal.ski',
    by: 'Emil Kowalski',
    why: 'Almost nothing on the page, and all of it considered: small type, soft grey, generous space. The craft lives in the projects it links to (Sonner, Vaul, animations.dev).',
    lessons: ['Restraint is a style', 'Let the work carry the personality', 'Explain the why next to the demo, as his articles do'],
    tags: ['motion', 'writing', 'personal'],
  },
  {
    id: 'darkroom',
    name: 'darkroom.engineering',
    url: 'https://darkroom.engineering',
    by: 'darkroom.engineering (makers of Lenis)',
    why: 'The studio behind Lenis commits to one idea: a red-on-black, terminal-and-darkroom aesthetic with display type stretched edge to edge.',
    lessons: ['One strong constraint (a single colour on black) reads as identity', 'Oversized type as layout', 'Open-source your tools and let the site prove them'],
    tags: ['scroll', 'typography', 'studio'],
  },
  {
    id: 'bruno-simon',
    name: 'Bruno Simon',
    url: 'https://bruno-simon.com',
    by: 'Bruno Simon',
    why: 'A portfolio you drive. The most famous proof that a personal site can be a game and still get the job done.',
    lessons: ['A concept can carry the whole site', 'Physics and playfulness make people share', 'Always offer a plain fallback for people in a hurry'],
    tags: ['three.js', 'game', 'personal'],
    settle: 20000,
    start: 'center',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    url: 'https://vercel.com',
    by: 'Vercel',
    why: 'Monochrome with one hero object: a black triangle with a soft glow, a two-line headline and nothing competing with either.',
    lessons: ['One object can carry a whole hero', 'Near-black on near-white, colour saved for product', 'Customer logos as quiet proof, set in greyscale'],
    tags: ['product', 'minimal', 'typography'],
    settle: 9000,
  },
  {
    id: 'raycast',
    name: 'Raycast',
    url: 'https://www.raycast.com',
    by: 'Raycast',
    why: 'A dark stage lit by grainy red light blades. The texture carries the brand, while the type stays centred, short and white.',
    lessons: ['Grain on gradients avoids banding and feels physical', 'Glass nav floating over a dark hero', 'One sentence of value, one download button'],
    tags: ['gradient', 'dark', 'product'],
    settle: 9000,
  },
  {
    id: 'framer',
    name: 'Framer',
    url: 'https://www.framer.com',
    by: 'Framer',
    why: 'The hero is the product working: an agent panel building a page in real time, framed by a glowing canvas.',
    lessons: ['Show the workflow, not a feature list', 'Two buttons, one primary', 'A single blue glow does the colour work on black'],
    tags: ['product', 'dark', 'ai'],
    settle: 9000,
  },
  {
    id: 'teenage',
    name: 'teenage engineering',
    url: 'https://teenage.engineering',
    dismiss: 'accept all',
    by: 'teenage engineering',
    why: 'Industrial-catalogue typography, hand-drawn illustration and a single orange accent. It reads like a printed product manual.',
    lessons: ['Heavy condensed display type as image', 'Illustration with a sense of humour', 'Navigation as an icon index, like a spec sheet'],
    tags: ['typography', 'illustration', 'brand'],
    settle: 9000,
  },
  {
    id: 'family',
    name: 'Family',
    url: 'https://family.co',
    by: 'Family (Aave Labs)',
    why: 'Playful, rounded character illustration makes a crypto wallet feel friendly. Colour lives in the drawings; the UI stays white and calm.',
    lessons: ['Personality through illustration, not UI chrome', 'Big, tight, friendly headline', "Soft pill buttons that match the illustration's roundness"],
    tags: ['illustration', 'friendly', 'product'],
    settle: 9000,
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    url: 'https://www.cosmos.so',
    by: 'Cosmos',
    why: 'A cloud of tilted image cards drifting around one centred headline. The content is the decoration.',
    lessons: ["Let the product's own content be the hero art", 'Calm serif-free type, tight tracking', 'Motion that feels like browsing, not showing off'],
    tags: ['gallery', 'motion', 'minimal'],
    settle: 9000,
  },
  {
    id: 'basement',
    name: 'basement.studio',
    url: 'https://basement.studio',
    by: 'basement.studio',
    why: 'A voxel-dithered 3D world on black, with a tiny HUD-like UI and a HUMAN / MACHINE toggle. Studio as a game level.',
    lessons: ['Dithering gives 3D a signature texture', 'Keep UI tiny when the canvas is the brand', 'One playful control invites exploration'],
    tags: ['webgl', '3d', 'studio'],
    settle: 9000,
  },
  {
    id: 'locomotive',
    name: 'Locomotive',
    url: 'https://locomotive.ca',
    by: 'Locomotive',
    why: 'Out-of-focus red type as the background and a sharp serif lockup in the corner. Depth of field used as a layout tool.',
    lessons: ['Blur separates layers without boxes', 'Mixed serif and cyan accent for a signature lockup', 'Confident corner placement over centred text'],
    tags: ['typography', 'motion', 'studio'],
    settle: 9000,
  },
  {
    id: 'joshcomeau',
    name: 'Josh W. Comeau',
    url: 'https://www.joshwcomeau.com',
    by: 'Josh W. Comeau',
    why: 'A blog with a character, a hand-made rainbow and sound. Warm, playful craft that still puts reading first.',
    lessons: ['A mascot makes a personal brand memorable', 'Magenta labels as a single accent for navigation', 'Long-form layout with a clear sidebar of categories'],
    tags: ['personal', 'illustration', 'writing'],
    settle: 9000,
  },
  {
    id: 'poolsuite',
    name: 'Poolsuite',
    url: 'https://poolsuite.net',
    by: 'Poolsuite',
    why: 'A fully committed retro-OS world: window chrome, 1997 dates, a pink desk and a working radio player.',
    lessons: ['Commit to a concept all the way down to the clock', 'Nostalgia works when details are researched', 'The player is real, so the costume has a function'],
    tags: ['concept', 'retro', 'music'],
    settle: 9000,
  },
  {
    id: 'br95',
    name: 'BR95: brunojaamaa.dev',
    url: 'https://brunojaamaa.dev',
    by: 'Bruno Jaamaa',
    why: 'A portfolio that pretends to be a Windows 95 computer without paying the SEO price: real routes and server HTML inside window chrome.',
    lessons: ['A concept backed by research reads as craft, not costume', 'Parity rule: a window and its route render the same server component', 'Constraints (one sanctioned colour) make a system'],
    tags: ['case study', 'three.js', 'concept'],
    settle: 5000,
    start: 'START',
    mine: true,
  },
];
