/*
 * pnpm gen: regenerate files derived from toolkit/toolkit.json and data/examples.json.
 *  - GALLERY.md: every example screenshot, by section (visible on GitHub)
 *  - README.md: 3 examples per section between <!-- gallery:begin --> and <!-- gallery:end -->
 *  - README.md: the table between <!-- toolkit:begin --> and <!-- toolkit:end -->
 *  - AGENTS.md: the full agent brief (rules + toolkit)
 * The site's Toolkit page and /llms.txt read the JSON directly, so they need no step.
 */
import { readFile, writeFile } from 'node:fs/promises';
import toolkit from '../toolkit/toolkit.json';
import examplesData from '../data/examples.json';

type Ex = { id: string; name: string; url: string; by?: string; note: string; image: string };
const examples = examplesData as Record<string, Ex[]>;

/* Section order and titles for the GitHub gallery. */
const SECTIONS: [string, string][] = [
  ['typography', 'Typography'], ['colour', 'Colour'], ['darkmode', 'Dark mode'], ['layout', 'Layout & space'],
  ['hierarchy', 'Hierarchy'], ['hero', 'Heroes'], ['bento', 'Bento grids'], ['footer', 'Footers'],
  ['motion', 'Motion'], ['scroll', 'Scroll stories'], ['3d', '3D & WebGL'], ['shaders', 'Shaders & gradients'],
  ['components', 'Components'], ['saas', 'SaaS landing pages'], ['ecommerce', 'E-commerce'], ['portfolio', 'Portfolios'],
  ['editorial', 'Editorial'], ['specimen', 'Specimens & design systems'], ['ai', 'AI products'],
];
const slug = (t: string) => t.toLowerCase().replace(/&/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* A 3-column HTML table of screenshots. GitHub renders <table>/<img> in markdown. */
function grid(items: Ex[], width = 3) {
  const rows: string[] = [];
  for (let i = 0; i < items.length; i += width) {
    const cells = items.slice(i, i + width).map(
      (e) => `<td width="33%" valign="top"><a href="${e.url}"><img src="public${e.image}" alt="${e.name}" /></a><br/><b><a href="${e.url}">${e.name}</a></b><br/><sub>${e.note.replace(/</g, '&lt;')}</sub></td>`,
    );
    rows.push(`<tr>${cells.join('')}</tr>`);
  }
  return `<table>\n${rows.join('\n')}\n</table>`;
}

function gallery() {
  const total = Object.values(examples).reduce((n, v) => n + v.length, 0);
  const toc = SECTIONS.filter(([k]) => examples[k]?.length)
    .map(([k, t]) => `[${t} (${examples[k].length})](#${slug(t)})`)
    .join(' · ');
  const body = SECTIONS.filter(([k]) => examples[k]?.length)
    .map(([k, t]) => `## ${t}\n\n${grid(examples[k])}\n\n[↑ back to top](#gallery)`)
    .join('\n\n');
  return `# Gallery\n\n<!-- generated by \`pnpm gen\` from data/examples.json. Edit the JSON, not this file. -->\n\n**${total} real websites**, screenshotted and checked by eye, grouped by what they teach. Click any image to visit the live site. Screenshots belong to their owners and are shown for commentary.\n\n${toc}\n\n${body}\n`;
}

function readmePreview() {
  return SECTIONS.filter(([k]) => examples[k]?.length)
    .map(([k, t]) => `### ${t}\n\n${grid(examples[k].slice(0, 3))}\n\n[All ${examples[k].length} ${t.toLowerCase()} examples →](GALLERY.md#${slug(t)})`)
    .join('\n\n');
}

const cats = toolkit.categories as Record<string, string>;
const esc = (s: string) => s.replaceAll('|', '\\|');

function table() {
  const lines: string[] = [];
  for (const [key, label] of Object.entries(cats)) {
    const rows = toolkit.tools.filter((t) => t.category === key);
    if (!rows.length) continue;
    lines.push(`\n**${label}**\n`, '| Tool | What | Status |', '|---|---|---|');
    for (const t of rows) lines.push(`| [${t.name}](${t.url}) | ${esc(t.what)} | \`${t.mcp.status}\` |`);
  }
  return lines.join('\n');
}

async function main() {
  const readme = await readFile('README.md', 'utf8');
  const next = readme.replace(
    /<!-- toolkit:begin -->[\s\S]*<!-- toolkit:end -->/,
    `<!-- toolkit:begin -->\n<!-- generated by \`pnpm gen\` from toolkit/toolkit.json. Edit the JSON, not this table. -->\n${table()}\n\n<!-- toolkit:end -->`,
  );
  const withGallery = next.replace(
    /<!-- gallery:begin -->[\s\S]*<!-- gallery:end -->/,
    `<!-- gallery:begin -->\n<!-- generated by \`pnpm gen\` from data/examples.json -->\n\n${readmePreview()}\n\n<!-- gallery:end -->`,
  );
  await writeFile('README.md', withGallery);
  await writeFile('GALLERY.md', gallery());

  const agents = `# AGENTS.md

Instructions for coding agents working **with** this guide (reading it for a project) or **on** it (editing this repo).

## Using this guide on a project

When a person starts a new project or design task and points you here:

1. Read \`toolkit/toolkit.json\` and the Principles chapter (\`content/docs/principles/\`).
2. **Before designing anything**, propose a short list: 3–6 tools and 3–5 principles that fit *this* brief, each with one line on why.
3. Ask the person to choose. Don't install or apply anything they haven't picked.
4. Respect each tool's \`mcp.status\`: \`needs-key\` and \`dormant\` tools need the person to sign in or pay first. Say so rather than failing silently.

Non-negotiables from this guide:
- Honour \`prefers-reduced-motion\` in every animation. Pause off-screen loops.
- Prove motion with two frames ~1.5 s apart. A single screenshot proves nothing.
- Test at 390px wide with no horizontal scroll.
- Measure contrast (4.5:1 body text).
- Don't default to the fonts every generator uses. Choose type for the subject.

## Editing this repo

- Stack: Next.js 16 + Fumadocs + MDX + Tailwind 4. Content lives in \`content/docs\`.
- Every guide page follows: live demo → code → install → why it works → links.
- \`toolkit/toolkit.json\` is the single source of truth. After editing it, run \`pnpm gen\`.
- Showcase entries (\`lib/showcase.ts\`) credit and link the owner and never copy their code or assets. Capture with \`pnpm shots --only=<id>\`.
- Before committing: \`pnpm build\` and \`pnpm verify\` (needs \`pnpm start\` on :3000).

## Toolkit (${toolkit.tools.length} tools, updated ${toolkit.updated})
${table()}
`;
  await writeFile('AGENTS.md', agents);
  console.log(`README table + AGENTS.md regenerated from ${toolkit.tools.length} tools`);
}

main();
