/*
 * pnpm gen: regenerate files derived from toolkit/toolkit.json.
 *  - README.md: the table between <!-- toolkit:begin --> and <!-- toolkit:end -->
 *  - AGENTS.md: the full agent brief (rules + toolkit)
 * The site's Toolkit page and /llms.txt read the JSON directly, so they need no step.
 */
import { readFile, writeFile } from 'node:fs/promises';
import toolkit from '../toolkit/toolkit.json';

const cats = toolkit.categories as Record<string, string>;
const esc = (s: string) => s.replaceAll('|', '\\|');

function table() {
  const lines: string[] = [];
  for (const [key, label] of Object.entries(cats)) {
    const rows = toolkit.tools.filter((t) => t.category === key);
    if (!rows.length) continue;
    lines.push(`\n**${label}**\n`, '| Tool | What | Status |', '|---|---|---|');
    for (const t of rows) lines.push(`| [${t.name}](${t.url}) | ${esc(t.what)} | \`${t.mcp.status}\` |`);
  }
  return lines.join('\n');
}

async function main() {
  const readme = await readFile('README.md', 'utf8');
  const next = readme.replace(
    /<!-- toolkit:begin -->[\s\S]*<!-- toolkit:end -->/,
    `<!-- toolkit:begin -->\n<!-- generated by \`pnpm gen\` from toolkit/toolkit.json. Edit the JSON, not this table. -->\n${table()}\n\n<!-- toolkit:end -->`,
  );
  await writeFile('README.md', next);

  const agents = `# AGENTS.md

Instructions for coding agents working **with** this guide (reading it for a project) or **on** it (editing this repo).

## Using this guide on a project

When a person starts a new project or design task and points you here:

1. Read \`toolkit/toolkit.json\` and the Principles chapter (\`content/docs/principles/\`).
2. **Before designing anything**, propose a short list: 3–6 tools and 3–5 principles that fit *this* brief, each with one line on why.
3. Ask the person to choose. Don't install or apply anything they haven't picked.
4. Respect each tool's \`mcp.status\`: \`needs-key\` and \`dormant\` tools need the person to sign in or pay first. Say so rather than failing silently.

Non-negotiables from this guide:
- Honour \`prefers-reduced-motion\` in every animation. Pause off-screen loops.
- Prove motion with two frames ~1.5 s apart. A single screenshot proves nothing.
- Test at 390px wide with no horizontal scroll.
- Measure contrast (4.5:1 body text).
- Don't default to the fonts every generator uses. Choose type for the subject.

## Editing this repo

- Stack: Next.js 16 + Fumadocs + MDX + Tailwind 4. Content lives in \`content/docs\`.
- Every guide page follows: live demo → code → install → why it works → links.
- \`toolkit/toolkit.json\` is the single source of truth. After editing it, run \`pnpm gen\`.
- Showcase entries (\`lib/showcase.ts\`) credit and link the owner and never copy their code or assets. Capture with \`pnpm shots --only=<id>\`.
- Before committing: \`pnpm build\` and \`pnpm verify\` (needs \`pnpm start\` on :3000).

## Toolkit (${toolkit.tools.length} tools, updated ${toolkit.updated})
${table()}
`;
  await writeFile('AGENTS.md', agents);
  console.log(`README table + AGENTS.md regenerated from ${toolkit.tools.length} tools`);
}

main();
