import type { Experience } from './types';

/* Group g8 (v3): new showpieces. Components in components/experiences/<id>.tsx */
export const experiences: Experience[] = [
  {
    id: 'micro-bench',
    title: 'Micro-interaction Bench',
    blurb: 'Six everyday components (button, toggle, checkbox, tabs, input, toast) shown in every state at once, with a x0.25 slow-mo so you can see each detail.',
    tools: ['gsap', 'css'],
    stage: 'mono',
    kind: 'interaction',
    source: 'components/experiences/micro-bench.tsx',
    load: () => import('@/components/experiences/micro-bench'),
  },
  {
    id: 'fluid-colour-reveal',
    title: 'Fluid Colour Reveal',
    blurb: 'Your cursor paints colour through a black and white page: a fluid trail reveals the full-colour version underneath and slowly heals.',
    tools: ['r3f', 'glsl', 'threejs'],
    stage: 'colour',
    kind: 'shader',
    source: 'components/experiences/fluid-colour-reveal.tsx',
    load: () => import('@/components/experiences/fluid-colour-reveal'),
  },
  {
    id: 'velocity-ribbon',
    title: 'Velocity Ribbon Type',
    blurb: 'A headline printed on a 3D ribbon that twists and stretches with how fast you scroll or drag.',
    tools: ['r3f', 'drei', 'glsl', 'gsap'],
    stage: 'colour',
    kind: 'type',
    source: 'components/experiences/velocity-ribbon.tsx',
    load: () => import('@/components/experiences/velocity-ribbon'),
  },
  {
    id: 'particle-portrait',
    title: 'Particle Portrait',
    blurb: 'Tens of thousands of points morph between images, scattering on the way and settling into each picture.',
    tools: ['r3f', 'glsl', 'threejs', 'gsap'],
    stage: 'colour',
    kind: 'generative',
    source: 'components/experiences/particle-portrait.tsx',
    load: () => import('@/components/experiences/particle-portrait'),
  },
  {
    id: 'liquid-metal-mark',
    title: 'Liquid Metal Mark',
    blurb: 'A chrome blob that melts from one mark into the next, reflecting a studio light as it goes.',
    tools: ['ogl', 'glsl', 'gsap'],
    stage: 'mono',
    kind: 'shader',
    source: 'components/experiences/liquid-metal-mark.tsx',
    load: () => import('@/components/experiences/liquid-metal-mark'),
  },
  {
    id: 'infinite-zoom',
    title: 'Infinite Zoom',
    blurb: 'An endless zoom: a Win95 desktop, into a monitor, into a phone, into a pixel, and back to the desktop.',
    tools: ['ogl', 'glsl', 'canvas2d', 'gsap'],
    stage: 'win95',
    kind: 'retro',
    source: 'components/experiences/infinite-zoom.tsx',
    load: () => import('@/components/experiences/infinite-zoom'),
  },
  {
    id: 'reference-globe',
    title: 'Reference Globe',
    blurb: 'A dotted globe with glowing arcs between the studios whose work this guide studies; drag to spin, hover a dot to read the studio.',
    tools: ['r3f', 'glsl', 'threejs'],
    stage: 'mono',
    kind: '3d',
    source: 'components/experiences/reference-globe.tsx',
    load: () => import('@/components/experiences/reference-globe'),
  },
];
